&fras"d1.txt"
Dict ← {"" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine"
        "" "1" "2" "3" "4" "5" "6" "7" "8" "9"}
⊜□≠@\n.
≡(
  ⊃(
    ⊔
    regex "\\d|one|two|three|four|five|six|seven|eight|nine"
    Dict
    ⊗:
  | ⇌⊔
    regex "\\d|eno|owt|eerht|ruof|evif|xis|neves|thgie|enin"
    ∵⇌Dict
    ⊗:
  )
  +×10∩(⊢◿10)
)
/+

# oneight
# twone
# threeight
# fiveight
# sevenine
# eightwo
# eighthree
# nineight
